title: Brennan's Engineering Stuff
email:
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
Linkedin_username: Brennan Park
github_username: bpark176
minimal_mistakes_skin: "dirt"
search: False
 
# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-include-cache

author:
  name   : "Brennan Park"
  avatar : "https://i.pinimg.com/736x/c7/44/8e/c7448e77953683dc5c99f28ee8ad622b.jpg"
  bio    : "Seoul International School"
  links:
    - label: "South Korea"
      icon: "fas fa-fw fa-map-marker-alt"
      url: "https://www.google.com/maps/place/South+Korea"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/brennan-park7"
    - label: "Math SE"
      icon: "fab fa-fw fa-stack-exchange"
      url: "https://www.youtube.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: False
      comments: False
      share: False
      related: False
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

#Research:
#  type: liquid
#  path: /research/
