title: "Brennan's Stuff"
description: >-
  Site for projects, research, and notes.

# Project site settings (REQUIRED if repo is NOT bpark176.github.io)
url: "https://bpark176.github.io"
baseurl: "/bpark167-s-stuff"

minimal_mistakes_skin: "dirt"
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

include:
  - _pages

plugins:
  - jekyll-include-cache

author:
  name   : "Brennan Park"
  avatar : "https://i.pinimg.com/736x/c7/44/8e/c7448e77953683dc5c99f28ee8ad622b.jpg"
  bio    : "Seoul International School"
  links:
    - label: "South Korea"
      icon: "fas fa-fw fa-map-marker-alt"
      url: "https://www.google.com/maps/place/South+Korea"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/"
    - label: "Math SE"
      icon: "fab fa-fw fa-stack-exchange"
      url: "https://math.stackexchange.com/"

defaults:
  - scope: { path: "", type: posts }
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
  - scope: { path: "_pages", type: pages }
    values:
      layout: single
      author_profile: true
